/*자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기 */
-- level 3

-- # 22년 10월 16일에 대여가능한 정보를 담고 있는 컬럼 추가
SELECT
CAR_ID,

CASE WHEN START_DATE <= '2022-10-16'
AND '2022-10-16' <= END_DATE 
THEN '대여중'
ELSE '대여 가능' 
END AS AVAILABILITY

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE END_DATE >= '2022-10-16'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

-- 다른 풀이
SELECT CAR_ID, 
    CASE WHEN SUM(
        CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1
        ELSE 0
        END) > 0 THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

-- MAX 풀이
SELECT CAR_ID, 
         MAX(IF ('2022-10-16' BETWEEN START_DATE AND END_DATE, '대여중', '대여 가능') )
          AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
ORDER BY CAR_ID DESC