/*조건에 맞는 사용자와 총 거래금액 조회하기*/

-- # 총금액이 70이상인 사람 조회
SELECT
B.USER_ID, 
B.NICKNAME,
SUM(PRICE) AS TOTAL_SALES
FROM 
USED_GOODS_BOARD AS A 
LEFT JOIN 
USED_GOODS_USER AS B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY A.WRITER_ID
HAVING TOTAL_SALES >= 700000 
ORDER BY TOTAL_SALES