/*카테고리 별 도서 판매량 집계하기*/

-- # 22년 1월 카테고리 합산
-- # 도서 판매량과 총판매액 구분해야함!
SELECT
B.CATEGORY,
SUM(SALES) AS TOTAL_SALES
FROM
BOOK_SALES AS A
LEFT JOIN
BOOK AS B
ON A.BOOK_ID = B.BOOK_ID
WHERE A.SALES_DATE LIKE '2022-01-%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY