/*즐겨찾기가 가장 많은 식당 정보 출력하기*/
-- level 3

-- # 음식 종류별로 즐겨찾기수가 가장 많은 식당
-- # 틀린 이유를 좀 더 생각해보기
SELECT
FOOD_TYPE,
REST_ID,
REST_NAME,
MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC

-- 서브쿼리를 이용한 다른 풀이
SELECT
FOOD_TYPE,
REST_ID,
REST_NAME,
FAVORITES 
FROM REST_INFO
WHERE FAVORITES IN(
SELECT MAX(FAVORITES)
FROM REST_INFO
GROUP BY FOOD_TYPE
)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC