/*저자 별 카테고리 별 매출액 집계하기*/
-- 같은 코드로 작성했는데, 맞는경우가 있고, 틀린경우가 있는데 
-- 대체 뭐가 문제인지 모르겠다.
-- 일단 중요한 점은 TOTAL_SALES는 총 판매금액 SUM()을 이용해야 한다.
-- JOIN은 BOOK_SALES를 기준으로 LEFT JOIN 을 사용한다.

SELECT 
A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
SUM(BS.SALES*B.PRICE) AS TOTAL_SALES
FROM 
BOOK_SALES BS LEFT JOIN BOOK B ON BS.BOOK_ID=B.BOOK_ID
LEFT JOIN AUTHOR A ON B.AUTHOR_ID=A.AUTHOR_ID
WHERE BS.SALES_DATE LIKE '2022-01-%'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC