/*주문량이 많은 아이스크림들 조회하기*/

-- 조인방법 중에 UNION ALL로 조인하기 

SELECT FLAVOR
FROM (SELECT * FROM FIRST_HALF UNION ALL SELECT * FROM JULY) A
GROUP BY FLAVOR
HAVING SUM(TOTAL_ORDER)
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3