/*상품 별 오프라인 매출 구하기*/


SELECT B.PRODUCT_CODE, SUM(A.SALES_AMOUNT) * B.PRICE AS SALES
FROM OFFLINE_SALE AS A LEFT JOIN PRODUCT AS B 
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE