/*대여 기록이 존재하는 자동차 리스트 구하기*/

SELECT
DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A LEFT JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE = '세단' AND MONTH(A.START_DATE) = 10
-- # A.START_DATE LIKE '%10%'
ORDER BY CAR_ID DESC