/*서울에 위치한 식당 목록 출력하기*/

-- A 테이블과 B 테이블에서 REST_ID가 같지 않았다.
-- 따라서 조인 방법을 잘 생각해봐야 한다. 리뷰 스코어가 있는 식당을 기준으로 조인을 해야 하며 평균 점수가 NULL이 아니여야 한다.

SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW A JOIN REST_INFO B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING B.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, B.FAVORITES DESC

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS A RIGHT JOIN REST_REVIEW AS B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING A.ADDRESS LIKE '서울%' 
ORDER BY SCORE DESC, A.FAVORITES DESC