/*조건에 부합하는 중고거래 상태 조회하기*/

-- # 2022년 10월 5일에 등록된 중고거래 게시물 
-- # 거래상태가 SALES 판매중, RESERVED 예약중 DONE 거래완료
-- # 서브쿼리 안만들어두 됨.. 
SELECT
BOARD_ID, WRITER_ID, TITLE, PRICE, 
CASE WHEN STATUS = 'SALE' THEN '판매중'
WHEN STATUS = 'RESERVED' THEN '예약중' 
WHEN STATUS = 'DONE' THEN '거래완료' ELSE STATUS END AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05'
ORDER BY 1 DESC