/* 자동차 대여 기록 별 대여 금액 구하기*/
-- 서브쿼리를 위해 WITH 절 사용하였다

WITH VALUE AS 
(SELECT 
CAR.DAILY_FEE, CAR.CAR_TYPE, HIS.HISTORY_ID,
DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 AS PERIOD,
CASE 
WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 90 THEN '90일 이상'
WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 30 THEN '30일 이상'
WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 7 THEN '7일 이상'
ELSE 'NONE' END AS DURATION_TYPE

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS CAR
ON HIS.CAR_ID = CAR.CAR_ID
WHERE CAR.CAR_TYPE = '트럭')


SELECT VALUE.HISTORY_ID, 
    ROUND(VALUE.DAILY_FEE * VALUE.PERIOD * 
          (100 - IFNULL(PLAN.DISCOUNT_RATE,0)) / 100) AS FEE
FROM VALUE
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  AS PLAN 
    ON PLAN.DURATION_TYPE = VALUE.DURATION_TYPE 
    AND PLAN.CAR_TYPE = VALUE.CAR_TYPE
ORDER BY 2 DESC, 1 DESC

