/*취소되지 않은 진료 예약 조회하기*/


-- # 출력되는 열 순서가 같아야 한다.

SELECT
A.APNT_NO, B.PT_NAME, A.PT_NO, C.MCDP_CD, C.DR_NAME, A.APNT_YMD

FROM APPOINTMENT A LEFT JOIN PATIENT B ON A.PT_NO = B.PT_NO
LEFT JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID

WHERE A.APNT_YMD LIKE '2022-04-13%'
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY 6
