/*그룹별 조건에 맞는 식당 목록 출력하기*/
-- 리뷰를 가장 많이 작성한 회원의 리뷰를 조회
-- GROUP BY, COUNT, LIMIT 를 활용한 서브쿼리 작성

SELECT
B.MEMBER_NAME,
A.REVIEW_TEXT,
DATE_FORMAT(A.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE


FROM REST_REVIEW AS A
LEFT JOIN MEMBER_PROFILE AS B
ON A.MEMBER_ID = B.MEMBER_ID

WHERE A.MEMBER_ID = (
SELECT 
MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC LIMIT 1) 

ORDER BY REVIEW_DATE, REVIEW_TEXT
