/*5월 식품들의 총매출 조회하기*/
-- # 생산일자가 22년도 5월인 식품들 판매량 계산하여 정렬하기

SELECT 
A.PRODUCT_ID, 
A.PRODUCT_NAME,
SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES

FROM FOOD_ORDER AS B
LEFT JOIN FOOD_PRODUCT AS A
ON A.PRODUCT_ID = B.PRODUCT_ID

WHERE B.PRODUCE_DATE LIKE '2022-05%'
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID